volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
music mute: key(mute)
music next: key(next)
music previous: key(prev)
music (play | pause): user.play_pause()
